### PR TITLE
(#20) Definition Box Padding

### LINKED ISSUE #20: Add more padding bottom when there is no "Show full definition"
### Issue description
Padding bottom is too tight when there is no "Show full definition"

> **ESTIMATE** 1

### What's the expected change?
- Add 6px more padding-bottom after definition

### What's the current functionality?
- Padding is tight

### What's the updated acceptance criteria?
```gherkin
Scenario: User views search results page
  Given the user is viewing the page for a definition that does not have "Show full definition"
Then there will be more padding on the bottom of the definition content block
```

### Additional details / screenshot
https://react-app-dev.cancer.gov/sitewide-search-app/ticket__5-definition-display?cfg=0&swkeyword=Caloric%20Intake

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #20

* Added bottom margin to definition description

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@blilianyu 
Please review https://react-app-dev.cancer.gov/sitewide-search-app/bugfix__20-definition-box-padding?cfg=0&swkeyword=caloric%20intake

**Comment by blilianyu** [comment]
@seyilonge-nci Can you reduce it from 10px to 5px?

**Comment by seyilonge-nci** [comment]
@blilianyu Updated! Any better?

**Comment by blilianyu** [comment]
@seyilonge-nci  Looks great!!

**Comment by seyilonge-nci** [comment]
@blilianyu  Thanks!

**Pull request merged**
